
export const ITEMS = {
    config: {
        collection: "",
        helper_collection: ""
    },
    solape: {
        amount: 100_000,
        json: "https://arweave.net/PHUINOgLilPQTaoTwDExLsygXtpti8pS8l10Hk9iF4U",
        mint: "",
    },
    collection: {
        amount: 1,
        png:  "https://arweave.net/bxb0QFRZMl_zQDsKou0pbCMPQpxNZZSmfYXT1_A6MSk",
        json: "https://arweave.net/2Rydx48ahCOCM8yNCMpelXtU3c3vVd-T4Q54DhaU32Y",
        mint: "",
    },
    blueKey: {
        amount: 100_000,
        glb:  "https://arweave.net/4o3efioXVTMYAXCerFtpiYBdDzVOuPb4VxQGHsncfk4",
        png:  "https://arweave.net/gN9IcD4T4l7d71c1v5xTlVsvn0ByT-QyRNI3DE_002c",
        json: "https://arweave.net/XXhZKugN3l_N1A5NwhGImQcv_vbzHnbf2OoqrIoc5-k",
        mint: "",
    },
    greenKey: {
        amount: 100_000,
        glb:  "https://arweave.net/tkoOiBTlSuX-Y6W9lR2UB-3VVGyxMijnGe4Ld2k8fU0",
        png:  "https://arweave.net/_MGeR0cyzolMNtWYrIDRQCEhi-27UmlizGVNhy7Fih4",
        json: "https://arweave.net/7qawsjan95U-XzSDurWd5ZiwnrdrQI16cXu6oEBhzAI",
        mint: "",
    },
    purpleKey: {
        amount: 100_000,
        glb:  "https://arweave.net/yKQlwpI5K7PdDAmCfmFR6v_oWzKh0wjFtlDF25QtRks",
        png:  "https://arweave.net/SIO8pPCSCsqg0kM9fGNXOQohDHhNPJ8n8Lwv_tjyfQg",
        json: "https://arweave.net/LRMSkMic55HUHgxt_wIF4B0kz_0J1VcZY9bzsOQTfRI",
        mint: "",
    },
    brokenKey: {
        amount: 100_000,
        glb:  "https://arweave.net/gRstBO0S-Vnbdn22kypf03JOFZUmw7UCA3QRTHZZAq8",
        png:  "https://arweave.net/JJKLXJlhi-pYHxnEFKCMpEZ5TPU5vmmFvwEDlQ_pTAM",
        json: "https://arweave.net/dlF16GZA74q3pRytWjif9yLxoG9VfTd4-bB0mvnXv-k",
        mint: "",
    },
    blackKey: {
        amount: 100_000,
        glb:  "https://arweave.net/K8YTuVuGoZNRMxbXv_I8bv6rEKiR9jzmKCn5imsntN4",
        png:  "https://arweave.net/g-TP4O-jaipEg8M0jmZEuqE6y_WfHNOOmj6HuyqPIxs",
        json: "https://arweave.net/9_-tVwfsr8OCjAR6owefuIRaw66Mef5Gvy17hY2pjcA",
        mint: "",
    },
    whiteKey: {
        amount: 100_000,
        glb:  "https://arweave.net/MPl_90mVS_QbSXEqkfpReyJUKHlvvPD4-v_JWR3o9H0",
        png:  "https://arweave.net/l-CB7NTWakvvH5a7S2tvEv01ezGIsHGFbD0VvJSJR-0",
        json: "https://arweave.net/TQj24Sjh3jQgGMlTwK3iRltdLWlVZ5Cvdn0Mnny9eDQ",
        mint: "",
    },
    blackChest: {
        amount: 100_000,
        glb:  "https://arweave.net/9g9YZs7d7NDBhwvFkO_Qdy7mwZ70n5yit2kcUw6aa_Q",
        png:  "https://arweave.net/VtE-w4_ww1eAp1-HAH56owHSxsax1Vk40mYXPgTQKfY",
        json: "https://arweave.net/PkbNFqvSEWc2CcN4Dn0-1DIQm_EF3HabXGrwD46akxs",
        mint: "",
    },
    whiteChest: {
        amount: 100_000,
        glb:  "https://arweave.net/XYi7FggKw5Dr2gfEWmAf7ZflLOEudl1yxJiY4vdvdM0",
        png:  "https://arweave.net/-8YP86JTb3P8rRI4k4opFS0EeBUU09bZgLQ0FNDTY-E",
        json: "https://arweave.net/QZweORO0axxwB8OMRYhUK7B8ntgmwZnGtWKYfNVBe8Y",
        mint: "",
    },
    replayToken: {
        amount: 100_300,
        glb:  "https://arweave.net/MtyZ1n5soAmvC6NTaabaotEVdvxp6yKMjSX--yNYA0U",
        png:  "https://arweave.net/AVwhbS2Zc8sIOcgEIaTDCRhh-enHdpzNqZURNVFm_eI",
        json: "https://arweave.net/ZF6r1pKXBAnGfO9R8tletIFgiOPYYMAqBKQHhdBftTY",
        mint: "",
    },
    realTreasure: {
        amount: 100_000,
        glb:  "https://arweave.net/HR-ALR1ClAJzyQvVoJPvzDhxJADhYyukzME-SnqatjY",
        png:  "https://arweave.net/fH2z2n3Q5UwlpvyM4N79d6Bfo_ZDuZBSfKJOdbYfvHU",
        json: "https://arweave.net/w_3hJXfAvKz1ryxyvRkgJx1FIRhOkXVZ9H1uAUolKGM",
        mint: "",
    },
    redHerring: {
        amount: 100_000,
        glb:  "https://arweave.net/hpaeDL3WmvF01O7Pw8YNZKmRGxdjpdYVfy744y8-Bio",
        png:  "https://arweave.net/-GqSJ5iZhIeTg70gmZEKp4_JxDwwBVapTaMJFi13Wgc",
        json: "https://arweave.net/C3v1i4Qd7xn7Vqi0QC829N3bp0B6kQ0LVzaTdbMlcj8",
        mint: "",
    },
    fakeNoot: {
        amount: 1,
        json: "https://arweave.net/DxiyfXrJOlLHPHszlSSdK-nXv0Z7GeNZ8ylJiXkrNes",
        mint: "",
    },
    clue1: {
        amount: 1,
        png:  "https://arweave.net/anEbj2gI1xqqr7raf40lgWgUjVuzRqn8nDcenxVlnL4",
        json: "https://arweave.net/MyOjvcD2MaxMe0-jJccnIN29MADM-x32DAiN3wCR-xw",
        mint: "",
    },
    clue2: {
        amount: 1,
        png:  "https://arweave.net/euCxtEweDD7jR8BLjb97WxB3vGYcjMhRs4eZxKCBaTE",
        json: "https://arweave.net/tfNCtsNeeXq9qPxPF5NC4RmwDwMXIWXAdkDlv1TGscU",
        mint: "",
    },
    clue3: {
        amount: 1,
        png:  "https://arweave.net/5S203RnAfGJCpnpFITjen5jnfVSn3J81ygRMJO5MhPU",
        json: "https://arweave.net/84xg_lF8TRTQVQ9VKBejn7TAOzv1pVWEvDcYd6SuuFU",
        mint: "",
    },
    clue4: {
        amount: 1,
        png:  "https://arweave.net/FmtXHdwu7_c9-6z_6zq3xN3R89d7djpGxbHLZpW9QLQ",
        json: "https://arweave.net/PpHciuIj0RIrL0PtVORYNKpzxgMNloaeeVejBN5j1u0",
        mint: "",
    },
    clueTitle: {
        amount: 1,
        png:  "https://arweave.net/bHO8CxEOZEcwx42Oej6F3HsjPXF8uYY8YMq_0n0OtO8",
        json: "https://arweave.net/Tjoi4uMEBRHb0Bu1ce4iKMOEwfR7I3KE8ZgUQsYzL9k",
        mint: "",
    },
    greenChest: {
        amount: 1,
        glb:  "https://arweave.net/88Nq6kThK6EzlNavEmo0riwvC1vTgstPxCi4j_JhmQw",
        json: "https://arweave.net/5ZJ2Y97gBaJdYp1P-zNcqTlhDFXp2q5K21mwdGgjyLM",
        mint: "",
    },
    blueChest: {
        amount: 1,
        glb:  "https://arweave.net/9iBVnYBlOmHaf41i3LQ6-lDrXVs76jpbe69NjJRXaho",
        json: "https://arweave.net/vlTlTSzx_xBHWJObstiMxa310iKHk5YA62PApjtxkQ4",
        mint: "",
    },
    purpleChest: {
        amount: 1,
        glb:  "https://arweave.net/JAPkROSTvxeFmG5mY3n9RfzMgKXf3qNuM9DrbheD75k",
        json: "https://arweave.net/haSEU87jSTeUr6FYFYE4asW6O9816n8RvcvkaZncu1Q",
        mint: "",
    },
}